### ISSUE TITLE
Show Stations

### ISSUE THREAD

**Issue by Nimo-19** [Nature40/SENSO-Trail-App#2]
#### Story
*As a*
User
*I want to*
see a station
*so I could*
see its tasks
#### Tasks
- [x] station list view
- [x] station view
- [x] load all Stations of a trail
- [x] setup station data
