### ISSUE TITLE
Read Text Activity

### ISSUE THREAD

**Issue by Nimo-19** [Nature40/SENSO-Trail-App#5]
#### Story
*As a*
User
*I want to*
read a stations informative text
*so I could*
learn something
#### Tasks
- [x] read text view
- [x] setup activitys in Stations
- [x] setup text-activity data
