### ISSUE TITLE
Multiple Choice Activity

### ISSUE THREAD

**Issue by Nimo-19** [Nature40/SENSO-Trail-App#7]
#### Story
*As a*
User
*I want to*
answer a multiple choice question at a station
*so I could*
prove my knowledge
#### Tasks
- [x] multiple choice view
- [x] setup multiple choice activity data
- [x] add multiple choice data loading to activity loading
- [x] add view to activity wrapper
- [x] handle choosing and revealing answers
