### ISSUE TITLE
Next Station

### ISSUE THREAD

**Issue by Nimo-19** [Nature40/SENSO-Trail-App#8]
#### Story
*As a*
User
*I want to*
be able to go to the next station only if i completet the current station
*so I could*
follow the trail in the proposed order 
#### Tasks
- [x] measure completness of station
- [x] order stations
- [x] make next station accesible if current station is finished

**Comment by Nimo-19** [comment]
#### notes todo
- [ ] fix tests 
- [ ] add tests for additional station epics and actions
- [ ] add tests for additional trail actions
