### ISSUE TITLE
Offline data

### ISSUE THREAD

**Issue by Nimo-19** [Nature40/SENSO-Trail-App#9]
#### Story
*As a*
User
*I want to*
be able to access the data I loaded early, even if I'm offline at the moment
*so I could*
participate in the trail, even if my connectivity is low
#### Tasks
- [x] setup service worker
- [x] setup api data caching
- [x] setup state caching
